#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/quagga/zebra.conf ] ; then
    echo "Starting Quagga (zebra)"

    exec \
        /usr/lib/quagga/zebra
else
    # Otherwise sleep for a while...
    sleep 60
fi
