#!/usr/bin/with-contenv bash

# If config file exists, start daemon
if [ -f /etc/quagga/ospf6d.conf ] ; then
    echo "Starting Quagga (ospf6d)"

    exec \
        /usr/lib/quagga/ospf6d
else
    # Otherwise sleep for a while...
    sleep 60
fi
